### PR TITLE
Add 2 Player support

### PR DESCRIPTION
**Pull request by AnkanHalder**
- Adds an offline Two Player support to play with friends apart from the already existing Single Player(Vs Computer) Mode
- Updates UI  to show which Player has to make the current move

### CODE REVIEW

**Review by MrNullus — APPROVED** [review]
good code, is ok

**Review by franius8 — CHANGES_REQUESTED** [review]
The code work, but the buttons for choosing game mode are hidden and the user needs to first click start game and then scroll up. This is very unintuitive. Maybe it would be better to replace the current start button with two button for different game modes?

**Review by franius8 — APPROVED** [review]
The code looks good now. Great work!

**Review by MrNullus — COMMENTED** [review]
ok

**Pull request merged**
